import type { Metadata } from "next";
import Link from "next/link";
import { MobileHeader } from "@/components/MobileHeader";

export const metadata: Metadata = { title: "Termos de uso" };

export default function TermsPage() {
  return <><MobileHeader title="Termos de uso" backHref="/guia" /><main id="conteudo"><header className="brand-pattern border-b border-[var(--leaf-strong)]"><div className="page-shell max-w-4xl py-10 lg:py-14"><p className="eyebrow">Uso do guia</p><h1 className="mt-2 text-4xl font-bold text-[var(--forest)] lg:text-5xl">Termos de uso</h1><p className="mt-3 text-sm text-[var(--muted)]">Versão de 12 de agosto de 2026.</p></div></header><div className="page-shell max-w-4xl py-10"><div className="space-y-4 leading-7 text-[var(--muted)]"><section className="card-surface p-6"><h2 className="text-xl font-bold text-[var(--forest)]">Finalidade</h2><p className="mt-2">O Guia Aroeira reúne informações de estabelecimentos do entorno para consulta. Endereços, contatos, avaliações, distâncias e preços podem mudar; confirme as condições diretamente com o estabelecimento antes de se deslocar ou comprar.</p></section><section className="card-surface p-6"><h2 className="text-xl font-bold text-[var(--forest)]">Endereços e navegação</h2><p className="mt-2">O guia não oferece mapa ou cálculo de rotas nesta versão. O usuário pode copiar o endereço e consultá-lo no aplicativo de navegação de sua preferência. Confirme o destino antes de iniciar o deslocamento.</p></section><section className="card-surface p-6"><h2 className="text-xl font-bold text-[var(--forest)]">Conteúdo demonstrativo</h2><p className="mt-2">As áreas de transporte, candidatura a parceria e benefícios continuam identificadas como demonstração e não representam ofertas, linhas ou compromissos oficiais.</p></section><section className="card-surface p-6"><h2 className="text-xl font-bold text-[var(--forest)]">Uso responsável</h2><p className="mt-2">Não tente interferir no funcionamento do guia, extrair dados em massa ou usar o serviço para finalidade ilícita. Estes termos podem ser atualizados quando o produto ou suas fontes mudarem.</p></section></div><Link href="/guia" className="button-secondary mt-8">← Voltar ao guia</Link></div></main></>;
}
