"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import type { Establishment } from "@/data/types";
import { defaultFoodFilters, deriveFoodOptions, filterFoodEstablishments, parseFoodState, serializeFoodState, sortFoodEstablishments, type FoodFilters, type FoodSort } from "@/lib/establishment-rules";
import { CompactEstablishmentCard } from "./CompactEstablishmentCard";
import { EstablishmentCard } from "./EstablishmentCard";
import { GuideIcon } from "./GuideIcon";
import { EmptyState } from "./States";

function FilterControls({ filters, onChange, establishments, idPrefix }: { filters: FoodFilters; onChange: (next: FoodFilters) => void; establishments: Establishment[]; idPrefix: string }) {
  const options = useMemo(() => deriveFoodOptions(establishments), [establishments]);
  const fieldClass = "field-control mt-1 text-sm";
  return <div className="space-y-4">
    <div><label className="block text-sm font-bold" htmlFor={`${idPrefix}-group`}>Grupo</label><select id={`${idPrefix}-group`} className={fieldClass} value={filters.group} onChange={(event) => onChange({ ...filters, group: event.target.value })}><option value="">Todos</option>{options.groups.map((group) => <option key={group}>{group}</option>)}</select></div>
    <div><label className="block text-sm font-bold" htmlFor={`${idPrefix}-ticket`}>Ticket máximo</label><select id={`${idPrefix}-ticket`} className={fieldClass} value={filters.ticketMax ?? ""} onChange={(event) => onChange({ ...filters, ticketMax: event.target.value ? Number(event.target.value) : null })}><option value="">Qualquer valor</option><option value="40">Até R$ 40</option><option value="60">Até R$ 60</option><option value="100">Até R$ 100</option></select></div>
    <div><label className="block text-sm font-bold" htmlFor={`${idPrefix}-distance`}>Distância máxima</label><select id={`${idPrefix}-distance`} className={fieldClass} value={filters.maxDistanceMeters ?? ""} onChange={(event) => onChange({ ...filters, maxDistanceMeters: event.target.value ? Number(event.target.value) : null })}><option value="">Qualquer distância</option><option value="300">Até 300 m</option><option value="500">Até 500 m</option><option value="1000">Até 1 km</option></select></div>
  </div>;
}

export function FoodExplorer({ establishments }: { establishments: Establishment[] }) {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const [initial] = useState(() => parseFoodState(new URLSearchParams(searchParams.toString())));
  const [filters, setFilters] = useState(initial.filters); const [sort, setSort] = useState<FoodSort>(initial.sort);
  const result = useMemo(() => sortFoodEstablishments(filterFoodEstablishments(establishments, filters), sort), [establishments, filters, sort]);
  const query = useMemo(() => serializeFoodState(filters, sort), [filters, sort]);
  useEffect(() => { router.replace(query ? `${pathname}?${query}` : pathname, { scroll: false }); }, [pathname, query, router]);
  const clear = () => { setFilters(defaultFoodFilters); setSort("distance"); };
  const sortControl = (id: string) => <label className="flex items-center gap-2 text-sm font-bold text-[var(--forest)]" htmlFor={id}>Ordenar<select id={id} value={sort} onChange={(event) => setSort(event.target.value as FoodSort)} className="min-h-11 rounded-xl border border-[var(--line)] bg-white px-3 font-normal text-[var(--ink)]"><option value="distance">Menor distância</option><option value="ticket">Menor ticket</option><option value="name">Nome</option></select></label>;
  return <>
    <div className="lg:hidden"><div className="space-y-3 px-4 py-4"><label className="relative block" htmlFor="mobile-food-search"><span className="sr-only">Pesquisar por nome</span><GuideIcon name="search" className="pointer-events-none absolute left-4 top-3.5 h-5 w-5 text-[var(--muted)]" /><input id="mobile-food-search" type="search" placeholder="Pesquisar estabelecimento" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} className="field-control pl-12" /></label><div className="flex gap-2 overflow-x-auto pb-1">{[300, 500, 1000].map((meters) => <button key={meters} type="button" aria-pressed={filters.maxDistanceMeters === meters} onClick={() => setFilters({ ...filters, maxDistanceMeters: filters.maxDistanceMeters === meters ? null : meters })} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm font-bold ${filters.maxDistanceMeters === meters ? "border-[var(--forest)] bg-[var(--forest)] text-white" : "border-[var(--line)] bg-white text-[var(--muted)]"}`}>Até {meters === 1000 ? "1 km" : `${meters} m`}</button>)}</div><details className="rounded-xl border border-[var(--line)] bg-[var(--soft)] p-3"><summary className="flex min-h-11 items-center font-bold text-[var(--forest)]">Todos os filtros</summary><div className="mt-3"><FilterControls filters={filters} onChange={setFilters} establishments={establishments} idPrefix="mobile" /></div></details><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-[var(--muted)]" aria-live="polite"><strong className="text-[var(--ink)]">{result.length}</strong> opções</p>{sortControl("mobile-sort")}</div></div><div className="space-y-3 px-4 pb-24">{!result.length ? <EmptyState description="Nenhum estabelecimento combina com os filtros selecionados." onClear={clear} /> : result.map((item) => <CompactEstablishmentCard key={item.slug} establishment={item} returnQuery={query} />)}</div></div>
    <div className="hidden min-h-[calc(100vh-14rem)] grid-cols-[18rem_minmax(0,1fr)] border-y border-[var(--line)] bg-white lg:grid"><aside className="border-r border-[var(--line)] bg-[var(--soft)] p-6"><h2 className="text-lg font-bold text-[var(--forest)]">Filtrar opções</h2><div className="mt-5"><FilterControls filters={filters} onChange={setFilters} establishments={establishments} idPrefix="desktop" /></div><button type="button" onClick={clear} className="button-secondary mt-5 w-full">Limpar filtros</button></aside><section className="p-7"><div className="mb-5 flex items-center justify-between gap-3"><p className="text-sm text-[var(--muted)]"><strong className="text-[var(--ink)]">{result.length}</strong> opções encontradas</p>{sortControl("desktop-sort")}</div><label className="relative mb-6 block"><span className="sr-only">Pesquisar estabelecimento ou tipo</span><GuideIcon name="search" className="pointer-events-none absolute left-4 top-3.5 h-5 w-5 text-[var(--muted)]" /><input type="search" aria-label="Pesquisar estabelecimento ou tipo" placeholder="Pesquisar estabelecimento ou tipo" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} className="field-control pl-12" /></label><div className="grid gap-5 xl:grid-cols-2">{!result.length ? <EmptyState description="Nenhum estabelecimento combina com os filtros selecionados." onClear={clear} /> : result.map((item) => <EstablishmentCard key={item.slug} establishment={item} returnQuery={query} />)}</div></section></div>
  </>;
}
